### ISSUE TITLE
made an elm version

### ISSUE THREAD

**Issue by michaelglass** [dsw/proquint#13]
just giving you a heads up! is pretty ugly but works

<3

-Michael
https://package.elm-lang.org/packages/michaelglass/proquint/latest/
https://github.com/michaelglass/proquint

**Comment by dsw** [comment]
Thanks.  If you want to add a pointer to your implementation to the
proquint page and send me a pull request, I will accept it.  Since it is in
another repo, put it under "Remote Implementations".
