### ISSUE TITLE
24-bit CSS color values?

### ISSUE THREAD

**Issue by twopoint718** [dsw/proquint#18]
It seems like this would be a nice way to talk unambiguously about CSS hex colors, e.g. "aquamarine" -> #7FFFD4. These color values are usually listed in 24-bit format and so isn't either 32 or 16-bit that would fit a proquint or proquint pair.

Maybe a proposal here is to always assume such colors are RGBA values, that is, 32 bits with the alpha channel included. #7FFFD4 becomes #7FFFD4FF (fully-opaque) and then converts to "luzuz-tiguz"

**Comment by dsw** [comment]
Proquints are at the string-of-bits layer of abstraction.  This request
speaks of a particular _interpretation_ of a string of bits, which is the
next abstraction layer up.  If you need to encode a string that is not an
integral number of proquints, perhaps just pad it with zeros.

**Comment by twopoint718** [comment]
Makes sense to me. Thanks for the comment!
