### ISSUE TITLE
Add a reference to the elixir implemenation

### ISSUE THREAD

**Issue by minhajuddin** [dsw/proquint#4]
I have done an elixir implemenation of this awesome scheme, would love to have a link pointing to it https://hex.pm/packages/proquint

**Comment by dsw** [comment]
Just edit the docs and submit it as pull request.

On Fri, Nov 11, 2016 at 4:38 AM, Khaja Minhajuddin <notifications@github.com

**Comment by minhajuddin** [comment]
Added pull request #5

**Comment by dsw** [comment]
I seem to have added this to the Readme long ago, so closing this.
